### ISSUE TITLE
xoa

### ISSUE THREAD

**Issue by stefraynaud** [xarray-contrib/xarray-contrib#11]
### Description

xoa is intended to help reading and manipulating observed and simulated ocean data. It is heavily based on [xarray](http://xarray.pydata.org/en/stable/).

For those who know it, it is the successor of [vacumm](https://github.com/VACUMM/vacumm) and will integrate with time some of its functionalities.

### Code Repository

https://github.com/VACUMM/xoa

### License

Apache-2.0

### Xarray Support

- [X] Yes

### PyPI/Conda-forge

- [X] Yes

### Documentation

- [X] A user guide or tutorial
- [X] Usage examples
- [X] API reference

### Unit Tests/Continuous Integration

- [X] Yes

### PEP8 compliant code style

- [X] Yes

**Comment by jhamman** [comment]
Hi @stefraynaud - sorry to let this sit for so long. We'd be happy to host Xoa here.

**Comment by stefraynaud** [comment]
@jhamman thank you for your answer.
While waiting to hear back, I proposed to my institute to create an organization to host our open-source codes. This is being discussed and if it works out, I will move xoa to this organization. 
I'll keep you informed.

**Comment by keewis** [comment]
@stefraynaud, can we close this, now that `xoa` lives in a shom-specific organization?

**Comment by stefraynaud** [comment]
Yes, absolutely, you can close it.
