### ISSUE TITLE
xvec

### ISSUE THREAD

**Issue by martinfleis** [xarray-contrib/xarray-contrib#12]
### Description

Xvec combines Xarray n-D arrays and shapely 2 planar vector geometries to create a support for vector data cubes in Python. It is a project me and @benbovy are currently working on that I believe would be happier here, rather than under my personal account.

If you want to know what vector data cubes are, see our [introduction](https://xvec.readthedocs.io/en/latest/intro.html) our [this blog post](https://r-spatial.org/r/2022/09/12/vdc.html).

I'd like to make a first release soon and thought it may be better to transfer the repo before that, if there would be an apetite from your side.

Not yet available on PyPI and conda-forge but will be once released.

### Code Repository

https://github.com/martinfleis/xvec

### License

MIT

### Xarray Support

- [X] Yes

### PyPI/Conda-forge

- [ ] Yes

### Documentation

- [X] A user guide or tutorial
- [X] Usage examples
- [X] API reference

### Unit Tests/Continuous Integration

- [X] Yes

### PEP8 compliant code style

- [X] Yes

**Comment by dcherian** [comment]
This looks like a perfect fit. Thanks @martinfleis 

I agree with releasing after transferring. It takes some work to update all the URLs after a release.

**Comment by dcherian** [comment]
I've created a `xvec-devs` team and added @martinfleis and @benbovy 

@benbovy should have the rights to do the transfer.

When you're ready, it'd be nice to advertise on a blog post at https://xarray.dev/blog

**Comment by jhamman** [comment]
> When you're ready, it'd be nice to advertise on a blog post at https://xarray.dev/blog

@martinfleis - if this is something you are up for, let me know I can help coordinate.

**Comment by martinfleis** [comment]
Thanks!

> @benbovy should have the rights to do the transfer.

I am actually not sure if he has the rights on the other side since xvec lives on my profile, not in another org.

> When you're ready, it'd be nice to advertise on a blog post at https://xarray.dev/blog

Happy to. I was planning on writing one for my blog so we can cross-post it. But it will happen at some point in March I guess.

**Comment by benbovy** [comment]
> I am actually not sure if he has the rights on the other side since xvec lives on my profile, not in another org.

@martinfleis I don't but I'm happy to take care of the transfer if you invite me on `martinfleis/xvec`.

**Comment by martinfleis** [comment]
@benbovy you have all rights you can I am afraid. I don't think you can give admin rights to a repo living under your personal profile to other user. -> https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository

**Comment by keewis** [comment]
that's weird, it should be possible for us to transfer the repository for you.

In any case, it seems that since you're a member of `xarray-contrib` now you should be able to do the transfer yourself.

**Comment by benbovy** [comment]
Ah I see. Now that you are a member of the xarray-contrib org, you should normally be able to do the transfer?

**Comment by martinfleis** [comment]
True :). Done - https://github.com/xarray-contrib/xvec

**Comment by martinfleis** [comment]
I will still need someone to assign `xvec-devs` group as admins to the xvec repo. Don't have an access to settings now.

**Comment by benbovy** [comment]
> I will still need someone to assign xvec-devs group as admins to the xvec repo. Don't have an access to settings now.

Done! (that's weird, though, you were already maintainer of both the xvec repo and the xvec team)

**Comment by keewis** [comment]
that's because we edited the roles in parallel. I wonder, though, if `xvec-devs` should only be maintainers?

**Comment by benbovy** [comment]
I set xvec-devs to admin. (sorry for the confusion)
