### ISSUE TITLE
xeofs

### ISSUE THREAD

**Issue by nicrie** [xarray-contrib/xarray-contrib#13]
### Description

 [Suggestion](https://github.com/pydata/xarray/pull/8561#issuecomment-1863056939)  of adding [xeofs](https://github.com/nicrie/xeofs) to xarray-contrib.

xeofs enables fully multidimensional PCA / EOF analysis and related techniques with large datasets, thanks to the integration of xarray and dask.

References:

- [Documentation](https://xeofs.readthedocs.io/en/latest/)
- [JOSS review](https://github.com/openjournals/joss-reviews/issues/6060)

### Code Repository

https://github.com/nicrie/xeofs

### License

MIT

### Xarray Support

- [X] Yes

### PyPI/Conda-forge

- [X] Yes

### Documentation

- [X] A user guide or tutorial
- [X] Usage examples
- [X] API reference

### Unit Tests/Continuous Integration

- [X] Yes

### PEP8 compliant code style

- [X] Yes

**Comment by dcherian** [comment]
I've created an xeofs-devs team and invited @nicrie  and @slevang

**Comment by dcherian** [comment]
I think you might have to add me as an admin on xeofs to actually transfer the repo

**Comment by nicrie** [comment]
Thanks! I think you should have admin rights now @dcherian

**Comment by dcherian** [comment]
I think I need more permissions unfortunately.

**Comment by keewis** [comment]
I'm not sure, but I think it might be enough that you have created the `xeofs` team (and possibly that's our only option). Once added, @nicrie should be able to transfer the repository here.

**Comment by dcherian** [comment]
Ah ok. @nicrie can you try the transfer please?

**Comment by nicrie** [comment]
I think it worked: https://github.com/xarray-contrib/xeofs :)
