### ISSUE TITLE
Transfering `xarray-regrid` to this organization

### ISSUE THREAD

**Issue by BSchilperoort** [xarray-contrib/xarray-contrib#14]
### Description

Regridding is a common operation in earth science and other fields. While xarray does have some interpolation methods available which can be used for, these are not always as straightforward to use within a regridding context. Additionally, methods such as [conservative regridding](https://earthsystemmodeling.org/regrid/#regridding-methods), or taking the most common value, are not available in xarray.

With xarray-regrid it is possible to regrid between two rectilinear grids. The following methods are supported:
- Linear
- Nearest-neighbor
- Conservative
- Cubic
- "Most common value" (zonal statistics)

### Code Repository

https://github.com/EXCITED-CO2/xarray-regrid

### License

Apache-2.0

### Xarray Support

- [X] Yes

### PyPI/Conda-forge

- [X] Yes

### Documentation

- [X] A user guide or tutorial
- [X] Usage examples
- [X] API reference

### Unit Tests/Continuous Integration

- [X] Yes

### PEP8 compliant code style

- [X] Yes

**Comment by rabernat** [comment]
Thanks for sharing @BSchilperoort. Xarray-regrid looks amazing! We have struggled to align on a performant, flexible solution in this space for years. I particularly appreciate the benchmarks and comparisons with CDO and ESMF.

I am strongly supportive of adding to xarray-contrib.

**Comment by dcherian** [comment]
Yes I agree. This is a great package!

**Comment by rabernat** [comment]
My one question, just out of curiosity, is the general scalability of the algorithms and the interoperability with Dask. Does it operate lazily? Can I use it efficiently on large datasets with a Dask cluster? Users will likely want to know this.

**Comment by BSchilperoort** [comment]
> Does it operate lazily? Can I use it efficiently on large datasets with a Dask cluster? Users will likely want to know this.

Most routines do. The linear/nearest/cubic regridders wrap xarray's `.interp`, so they do by default. The conservative method now also fully supports lazy operation thanks to @slevang (see https://github.com/EXCITED-CO2/xarray-regrid/pull/39#issue-2309187096).

The most-common-value operation does not support proper lazy computation yet. It [uses flox's `Aggregation`](https://github.com/EXCITED-CO2/xarray-regrid/blob/524c1c859c05741ebac62b7672c23ec1764c4fd8/src/xarray_regrid/methods/most_common.py#L174).  @dcherian made some changes to flox and [gave me some suggestions to improve this](https://github.com/xarray-contrib/flox/issues/263#issuecomment-2084358139) but I have not had the time yet to implement these.

**Comment by rabernat** [comment]
Awesome! I would recommend documenting everything you just told me prominently and also adding some dask-related tests to the test suite. (Not blockers in any way for moving the repo, just general suggestions for the package.)

**Comment by rabernat** [comment]
@BSchilperoort - since you are already a member of the `xarray-contrib` organization, you should be able to go ahead and make the repo transfer yourself.

**Comment by BSchilperoort** [comment]
> Awesome! I would recommend documenting everything you just told me prominently and also adding some dask-related tests to the test suite. (Not blockers in any way for moving the repo, just general suggestions for the package.)

I added the dask info to the main readme already. I'll create an issue about the tests :+1:

**Comment by BSchilperoort** [comment]
The repo has been transferred https://github.com/xarray-contrib/xarray-regrid :tada:

**Comment by dcherian** [comment]
nice!
