### ISSUE TITLE
Moving xarray-leaflet to xarray-contrib

### ISSUE THREAD

**Issue by davidbrochart** [xarray-contrib/xarray-contrib#4]
Reading the conditions to be included in xarray-contrib, I think [xarray-leaflet](https://github.com/davidbrochart/xarray_leaflet) is not quite ready yet, however I think it could make sense.
Would you consider transferring xarray-leaflet to this organization if we work on documentation, tests and CI, and code style?
[xtrude](https://github.com/davidbrochart/xtrude) could also be a candidate, although it is even at an earlier stage of development.

**Comment by keewis** [comment]
sorry for the late reply, @davidbrochart. I will bring this up in the meeting tomorrow, but I think this should be fine.

**Comment by keewis** [comment]
we discussed it and decided that it looks like a good fit for `xarray-contrib`. Feel free to ping us (me?) once you feel it's ready for the migration and we will guide you through the process.

**Comment by davidbrochart** [comment]
Thanks, now I just need to find some time to work on it :smile:

**Comment by dcherian** [comment]
@davidbrochart are you still interested in moving it over?

**Comment by davidbrochart** [comment]
I am, especially considering the potential use of [xpublish's XYZ endpoints](https://github.com/xarray-contrib/xpublish/pull/88).
But as I didn't find time to work on xarray-leaflet, I'm not sure we can move it as-is?

**Comment by davidbrochart** [comment]
It did: https://github.com/xarray-contrib/xarray_leaflet.
Thanks!
