### ISSUE TITLE
Move xwrf to xarray-contrib

### ISSUE THREAD

**Issue by jthielen** [xarray-contrib/xarray-contrib#6]
Over at https://github.com/ncar-xdev/xwrf/, several folks have been working on a package for working with [Weather Research and Forecasting (WRF)](https://www2.mmm.ucar.edu/wrf/users/) model output in xarray. Given the unfortunate departure of several of the NCAR xdev team members from NCAR, we'd like to have this package start being led by community maintainers (myself, with others TBD) and located here in xarray-contrib, if possible.

As far as I'm aware, xwrf currently meets all the guidelines for inclusion in xarray-contrib except being available on PyPI and/or conda-forge. And so, I'm hoping that creating an initial release could happen after the repo transfer!

**Comment by jthielen** [comment]
Sounds great! I've just been invited/added to the @xarray-contrib/xwrf-dev team (thanks @andersy005!), so should I go ahead and click the "Danger Zone" transfer button on xwrf? Or is there some condition we should wait for before making the move?

**Comment by andersy005** [comment]
I'm in favor of transferring the repository... 

Ccing @jhamman & @shoyer for their feedback

**Comment by shoyer** [comment]
+1, sounds good to me, as long as you're working towards that initial release!

**Comment by andersy005** [comment]
Done. Thank you!
