### ISSUE TITLE
Move xwrf-data to xarray-contrib

### ISSUE THREAD

**Issue by jthielen** [xarray-contrib/xarray-contrib#7]
Following up on https://github.com/xarray-contrib/xarray-contrib/issues/6, I forgot to mention that there is an accompanying data repository for xWRF: https://github.com/ncar-xdev/xwrf-data. Would there be any issues with moving this one over as well? Or would some other means for managing the package's data be preferred now under xarray-contrib?

**Comment by andersy005** [comment]
👍🏽 for transferring the data repository

**Comment by andersy005** [comment]
Done!
