### ISSUE TITLE
Transfer xarray-schema to this org

### ISSUE THREAD

**Issue by jhamman** [xarray-contrib/xarray-contrib#8]
We would like to transfer the xarray-schema project here. Xarray-schema is what its name suggests, a package for doing schema validation for Xarray objects. Its had a few minor releases and has some basic docs. 

- [x] Open-source license (MIT)
- [x] Supports a recent version of Xarray
- [x] Available on [PyPI](https://pypi.org/) and/or [conda-forge](https://conda-forge.org/)
- [x] Documentation sufficient for new users to get started, which typically includes:
  - [x] A user guide or tutorial
  - [x] Usage examples
  - [x] API reference
- [x] Unit tests + continuous integration
- [x] [PEP8](https://www.python.org/dev/peps/pep-0008/) compliant code style

cc: @andersy005, @freeman-lab, @norlandrhagen

**Comment by freeman-lab** [comment]
Sounds good to me!
